// Powered by Infostretch

timestamps {
    node ('GUI_Tests') {
        stage ('Checkout') {
            checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'henrygithub', url: 'git@github.com:HenryFBP/rivers-of-iron-mc.git']]])
        }
        stage ('Build') {
            // Unable to convert a build step referring to "hudson.plugins.build__timeout.BuildTimeoutWrapper". Please verify and convert manually if required.
            // Unable to convert a build step referring to "com.cloudbees.jenkins.GitHubSetCommitStatusBuilder". Please verify and convert manually if required.        // Batch build step
            bat '''packwiz refresh'''
            bat '''pipenv install'''
            bat '''pipenv run python scripts/pyautogui/test-with-pyautogui.py'''
        }
    }
}
